version: '3.8'
services:

  titanic-db:
    image: postgres:12-alpine
    container_name: titanic_db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=titanic
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password