server:
  port: 8081
spring:
  application:
    name: titanic
  datasource:
    url: jdbc:postgresql://localhost:6540/titanic
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  cache:
    type: simple

dataUrl: https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv